spring:
  data:
    redis:
      host: localhost
      port: 6379
  shell:
    interactive:
      enabled: true
  web:
    resources:
      static-locations: file:../uploads/
  datasource:
    password: postgres
    username: postgres
    url: jdbc:postgresql://localhost:5432/app_db
  jpa:
    generate-ddl: true

app:
  jwt:
    token: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855
    access: 10m
    refresh: 7d